---
apiVersion: v1
kind: Service
metadata:
  name: whatsapp-bot-service
spec:
  type: NodePort
  selector:
    app: whatsapp-bot
  ports:
    - port: 3000
      # targetPort: 3000
      # nodePort: 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: whatsapp-bot
spec:
  selector:
    matchLabels:
      app: whatsapp-bot # has to match .spec.template.metadata.labels
  serviceName: "whatsapp-bot-service"
  replicas: 1 # by default is 1
  minReadySeconds: 0 # by default is 0
  template:
    metadata:
      labels:
        app: whatsapp-bot # has to match .spec.selector.matchLabels
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: whatsapp-bot
        image: docker.io/bt66/whatsapp-bot:v1.1
        ports:
        - containerPort: 3000
          name: whatsapp-bot
        volumeMounts:
        - name: session-volume
          mountPath: /home/pptruser/whatsapp-bot/.wwebjs_auth
  volumeClaimTemplates:
  - metadata:
      name: session-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: ingress-whatsapp-bot
spec:
 rules:
 - host: whatsapp-restapi.bt66tech.my.id
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: whatsapp-bot-service
           port:
             number: 3000
 ingressClassName: nginx
